import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const require = createRequire(import.meta.url);
const knowledge = require('./knowledge.cjs');
const review = JSON.parse(await readFile(new URL('./pricing-questions.json', import.meta.url), 'utf8'));
const escape = value => String(value).replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
const destination = path.resolve('artifacts/boost-website-test/Boost-review-and-pricing.html');
const document = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Boost replies and pricing review</title><style>
*{box-sizing:border-box}body{margin:0;background:#111820;color:#edf4f8;font:16px/1.6 system-ui,sans-serif}main{max-width:980px;margin:auto;padding:36px 24px}h1{line-height:1.15;font-size:clamp(28px,5vw,44px)}h2{color:#72d2fa;margin-top:42px}h3{font-size:20px}p{max-width:78ch}a{color:#80d9ff}.lead{font-size:19px;color:#c9dce8}.note{border-left:3px solid #72d2fa;padding:14px 18px;background:#1b2935}article{padding:18px 0;border-bottom:1px solid #394b5a}article p{margin:7px 0}.evidence,small{color:#b4c5d1;font-size:14px}details{padding:14px 0;border-bottom:1px solid #394b5a}summary{cursor:pointer;font-weight:600;min-height:36px}details p{white-space:pre-wrap}.tag{color:#72d2fa;font-size:13px;font-weight:600;letter-spacing:.08em;text-transform:uppercase}nav{display:flex;gap:20px;flex-wrap:wrap}@media print{body{background:white;color:black}main{padding:0}.evidence,small{color:#333}h2,a{color:#12607a}article,details{break-inside:avoid}.note{background:#eef5f8}}
</style></head><body><main><div class="tag">PSI Performance · Private review · 9 October 2026</div><h1>Boost replies and pricing</h1><p class="lead">${knowledge.FAQS.length} prepared answers, guided account setup and booking help. Review the pricing questions below, then try the chat.</p><nav><a href="http://127.0.0.1:8780/website.html">Open private website preview</a><a href="#prices">Pricing decisions</a><a href="#answers">All prepared answers</a></nav><p class="note">Nothing is live. ${escape(review.status)} This local preview does not send messages, make bookings, take payments or access customer accounts. Store and enquiry links open public pages.</p><h2>Approved starting guides</h2>${Object.values(knowledge.PRICE_GUIDES).map(guide=>`<p>${escape(guide)}</p>`).join('')}<h2 id="prices">12 decisions for Matt</h2><p>Reply with the numbers and your answers. For any item, “quote only” is enough. Approved figures should state the vehicle group, inclusions, exclusions and whether GST is included.</p>${review.questions.map(q=>`<article><h3>${q.id}. ${escape(q.topic)}</h3><p>${escape(q.question)}</p><p class="evidence">Why this needs confirming: ${escape(q.evidence)}</p></article>`).join('')}
<h2 id="answers">Prepared replies</h2><p>Tap a question to read the exact draft answer. Longer account and booking guides can also be followed one step at a time in the chat.</p>${knowledge.FAQS.map(f=>`<details><summary>${escape(f.question)}</summary><p>${escape(f.reply)}</p><small>${escape(f.category)}. Sources: ${f.sources.map(s=>escape(knowledge.SOURCES[s])).join('; ')}.</small></details>`).join('')}<h2>Research and limits</h2><p>Reviewed PSI’s current public website, Apple and Google store listings, account and booking screens, saved project notes, and 22 selected Outlook messages. This is a targeted review, not an audit of every email. Personal customer details, individual quotes and private payment instructions are excluded from the bot.</p><p>The current engine uses prepared answers and explicit conversation rules. It can handle the tested wording and follow ups, but it is not an unrestricted AI assistant. Unknown questions remain for PSI. Real Shopify Inbox routing and alerts still require separate integration testing and approval.</p><p>Public sources: <a href="https://psiperformance.com.au/">PSI website</a>, <a href="https://psiperformance.com.au/pages/workshop-services-pakenham">workshop services</a>, <a href="https://psiperformance.com.au/pages/ev-hybrid">EV and hybrid</a>, <a href="https://psiperformance.com.au/pages/coding">coding</a>, <a href="https://psiperformance.com.au/pages/power-estimator">Power Estimator</a>.</p></main></body></html>`;
export function buildReviewDocument() { return document; }
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await mkdir(path.dirname(destination), { recursive: true });
  await writeFile(destination, document);
  console.log(JSON.stringify({ path: destination, answers: knowledge.FAQS.length, questions: review.questions.length }));
}
