// Fictional rehearsal conversations. No customer correspondence or private data.
module.exports = [
  { title: 'Routine service with an inclusion question', steps: [
    { say: 'How much to service my 2021 Audi RS3?', includes: ['423.50'], pending: 'mileage' },
    { say: '65000 kms', pending: 'details' },
    { say: 'Does that include spark plugs?', includes: ['inclusions'], pending: 'details' },
    { say: 'Resume quote', includes: ['Which service'] },
    { say: 'Annual service, no faults', pending: 'confirm', queued: false },
    { say: 'Yes, send it', queued: true, summary: ['2021', 'Audi', '65000', 'Annual service'] },
  ] },
  { title: 'VF shorthand and transmission follow ups', steps: [
    { say: 'How much for a tune?', includes: ['649'], pending: 'vehicle' },
    { say: '2016 VF auto', pending: 'details' },
    { say: 'Does that include the gearbox?', includes: ['Transmission tuning costs extra'], excludes: ['649'], pending: 'details' },
    { say: 'How much for that?', includes: ['Transmission tuning costs extra'], excludes: ['649'], work: 'transmission tuning' },
    { say: '6 speed auto, stock, smoother shifts', pending: 'confirm' },
    { say: 'Yep send it', queued: true, summary: ['2016 VF auto', '6 speed auto'] },
  ] },
  { title: 'Common spelling mistakes and short service replies', steps: [
    { say: 'hey how much for a servce?', includes: ['423.50'], pending: 'vehicle' },
    { say: 'Toyota Corolla', pending: 'year' },
    { say: '2018', pending: 'mileage' },
    { say: '90k', pending: 'details' },
    { say: 'just the annual one', pending: 'confirm' },
    { say: 'not yet', queued: false },
  ] },
  { title: 'Vehicle supplied before a build quote', steps: [
    { say: 'Do you build engines? I have a 2017 Holden Commodore.', includes: ['engine builds'] },
    { say: 'How much?', work: 'engine build', pending: 'details', excludes: ['What car'] },
    { say: 'Stock engine, street use, looking for a reliable rebuild', pending: 'confirm' },
    { say: 'Send it', queued: true, summary: ['2017', 'Holden', 'reliable rebuild'] },
  ] },
  { title: 'Correcting vehicle details during a quote', steps: [
    { say: 'Service price for a 2017 Toyota Corolla?', pending: 'mileage' },
    { say: 'Sorry it is a 2019 Mazda 3, not the Toyota', pending: 'mileage', year: '2019' },
    { say: '72000', pending: 'details' },
    { say: 'Logbook service', pending: 'confirm' },
    { say: 'Yes', queued: true, summary: ['2019', 'Mazda', '72000'] },
  ] },
  { title: 'Existing app user gets booking help without repeated downloads', steps: [
    { say: 'I already have the app', includes: ['Book ahead'] },
    { say: 'Is it free?', includes: ['free', 'optional'], excludes: ['AUD $423'], noStoreLinks: true },
    { say: 'How do I book?', includes: ['Book ahead'], noStoreLinks: true },
    { say: 'Guide me through a booking', includes: ['Step 1'], noStoreLinks: true },
    { say: 'Next', includes: ['Step 2'] },
  ] },
  { title: 'Android download and interrupted signup guide', steps: [
    { say: 'I have a Samsung phone, where do I get the app?', links: ['android'], excludes: ['iPhone App Store'] },
    { say: 'Guide me through account setup', includes: ['Step 1'], links: ['android'] },
    { say: 'Next', includes: ['Step 2'] },
    { say: 'My code hasnt arrived', includes: ['junk'] },
    { say: 'Resume guide', includes: ['Step 2'] },
    { say: 'Next', includes: ['Step 3'], excludes: ['tell me your code'] },
  ] },
  { title: 'iPhone download and account help', steps: [
    { say: 'Where can I download the PSI app?', links: ['apple', 'android'] },
    { say: 'iPhone', links: ['apple'] },
    { say: 'How do I make an account?', includes: ['Email my sign-in code', 'Save account details'] },
    { say: 'I forgot my password', includes: ['no PSI password'] },
  ] },
  { title: 'Website preference persists through availability questions', steps: [
    { say: 'I do not want the app, can I use the website?', includes: ['website'], links: ['enquiry'] },
    { say: 'When is the next available appointment?', includes: ['confirm', 'website'], excludes: ['In the app'], noStoreLinks: true },
    { say: 'How do I book?', includes: ['website'], links: ['enquiry'], excludes: ['Open Bookings'] },
  ] },
  { title: 'Two service questions in one message', steps: [
    { say: 'How much is a service? Does it include spark plugs?', includes: ['423.50', 'inclusions'], pending: 'vehicle', queued: false },
    { say: '2020 Hyundai i30', pending: 'mileage' },
    { say: '60000 km', pending: 'details' },
    { say: 'Annual service', pending: 'confirm' },
    { say: 'Yes send it', queued: true, summary: ['spark plugs', '2020 Hyundai i30'] },
  ] },
  { title: 'Safety takes priority over price', steps: [
    { say: 'How much is a service? My brakes failed, is it safe to drive?', includes: ['Do not drive', 'cannot alert PSI'], excludes: ['423.50'], queued: true },
    { say: 'Can I get a booking tomorrow?', queued: true, visitorLast: true },
  ] },
  { title: 'Unknown workshop prices remain for review', steps: [
    { say: 'How much for a custom roll cage?', excludes: ['649', '423.50'], pending: 'work' },
    { say: 'Custom roll cage', pending: 'vehicle' },
    { say: '2015 Ford Mustang', pending: 'details' },
    { say: 'Track use, need you to assess what is possible', pending: 'confirm' },
    { say: 'Not yet', queued: false },
  ] },
  { title: 'Stock and delivery are not invented', steps: [
    { say: 'Is this exhaust in stock?', includes: ['no live stock feed'], excludes: ['Yes. PSI'] },
    { say: 'Can it arrive tomorrow?', includes: ['confirm'], excludes: ['will arrive'] },
    { say: 'Website enquiry', links: ['enquiry'], queued: false },
  ] },
  { title: 'Exhaust quote distinguishes supply and fitting', steps: [
    { say: 'Exhaust quote for my 2018 Ford Mustang', pending: 'details' },
    { say: 'Rear section only, supplied and fitted, stock engine', pending: 'confirm' },
    { say: 'Does that include tuning?', includes: ['written quote'], queued: false },
    { say: 'Resume quote', pending: 'confirm' },
    { say: 'Yes please', queued: true, summary: ['Rear section', '2018'] },
  ] },
  { title: 'Coding compatibility and vehicle context', steps: [
    { say: 'Can you add CarPlay to my 2019 Mercedes?', includes: ['Compatibility'] },
    { say: 'How much would it cost?', pending: 'details', work: 'coding', excludes: ['423.50', '649'] },
    { say: 'Wireless CarPlay, original screen, no hardware changes yet', pending: 'confirm' },
  ] },
  { title: 'EV scope and battery rebuilding limit', steps: [
    { say: 'Do you service a BYD Shark?', includes: ['Service & Report'] },
    { say: 'Does the 423.50 cover every EV?', includes: ['confirm'], excludes: ['Yes.'] },
    { say: 'Can you rebuild the battery pack?', includes: ['not part of PSI'], queued: false },
  ] },
  { title: 'Optional Performance+ stays separate from workshop costs', steps: [
    { say: 'Do I need Performance+ to book?', includes: ['free', 'optional'], excludes: ['649'] },
    { say: 'What does Performance+ cost?', includes: ['9.99', '99.00'] },
    { say: 'Does that pay for my service?', includes: ['separately'], excludes: ['starts from'] },
  ] },
  { title: 'Existing booking changes require staff', steps: [
    { say: 'I need to reschedule my booking', includes: ['No booking has been changed'], queued: true },
    { say: 'Prefer Friday, if available', visitorLast: true, queued: true, summary: ['reschedule', 'Friday'] },
  ] },
  { title: 'Transport policy and arrival question reach the test inbox with context', steps: [
    { say: 'Can you organise interstate vehicle transport?', includes: ['arranged between you and your transport provider'], queued: false },
    { say: 'Message PSI', queued: true, summary: ['transport'] },
    { view: 'inbox' }, { reply: 'Test reply: Please arrange transport with your provider and confirm the arrival time with PSI.' },
    { view: 'customer', staffRead: true },
    { say: 'Thanks, it is a 2020 Ford Mustang', visitorLast: true, summary: ['2020', 'Ford Mustang'] },
  ] },
  { title: 'Consent is explicit and a question is not approval', steps: [
    { say: 'How much to service a 2019 Mazda 3 with 50000 km?', pending: 'details' },
    { say: 'Annual service', pending: 'confirm' },
    { say: 'Yes but does that include all fluids', includes: ['inclusions'], queued: false },
    { say: 'Not yet', queued: false },
  ] },
];
