'use strict';

// Curated public facts only. Private mail, individual quotes and customer data
// must never be copied into this module or the browser build.
(function (root) {
  const VERIFIED_ON = '2026-10-09';
  // Matt approved these as starting guides, not fixed quotes or package inclusions.
  const PRICE_GUIDES = Object.freeze({
    service: 'Service & Report starts from AUD $423.50 including GST. PSI confirms the final price for your vehicle and the work required.',
    dyno: 'Engine ECU dyno tuning starts from AUD $649 including GST. PSI confirms the final price for your vehicle and the work required. Transmission tuning costs extra. Some vehicles also need separately quoted unlocking or module work.',
    cam: 'For Holden and Chevrolet LS engines, entry cam packages start from AUD $3,450 + GST, which is AUD $3,795 including GST, drive in drive out. Includes fitting and engine ECU dyno tuning. PSI confirms eligibility, inspects the vehicle, and quotes any concerns or additional work for approval before proceeding. L77 and L76 require additional head removal, lifter and DOD work, quoted separately.',
  });
  const LINKS = Object.freeze({
    apple: { label: 'iPhone App Store', url: 'https://apps.apple.com/au/app/psi-performance-garage/id6806902732' },
    android: { label: 'Android Google Play', url: 'https://play.google.com/store/apps/details?id=com.psiperformance.booking' },
    enquiry: { label: 'Website enquiry', url: 'https://psiperformance.com.au/#booking-panel' },
    services: { label: 'Workshop services', url: 'https://psiperformance.com.au/pages/workshop-services-pakenham' },
    ev: { label: 'EV and hybrid services', url: 'https://psiperformance.com.au/pages/ev-hybrid' },
    shop: { label: 'PSI website shop', url: 'https://psiperformance.com.au/' },
    coding: { label: 'Coding information', url: 'https://psiperformance.com.au/pages/coding' },
  });
  const SOURCES = Object.freeze({
    website: 'PSI homepage, enquiry form and footer, checked 9 October 2026',
    workshop: 'PSI Workshop Services page, checked 9 October 2026',
    ev: 'PSI EV & Hybrid page, checked 9 October 2026',
    coding: 'PSI Coding page, compatibility information only, checked 9 October 2026',
    estimator: 'PSI Power Estimator, development notice checked 9 October 2026',
    stores: 'Public Australian Apple and Google Play listings, checked 9 October 2026',
    account: 'Current mobile account/index.tsx and account/sign-up.tsx, labels checked 9 October 2026',
    garage: 'Current mobile account setup and My Garage screens',
    booking: 'Current mobile booking.tsx, tabs/bookings.tsx and lib/booking.ts',
    pricingApproval: 'Matt confirmed Service & Report from AUD $423.50 and Dyno Tuning from AUD $649 on 9 October 2026. Starting guides only, with existing GST inclusive treatment. Exact prices and inclusions still require PSI review.',
    transmissionApproval: 'Matt confirmed on 9 October 2026 that transmission tuning is an extra cost, varying with the vehicle, transmission, setup and modifications. No fixed transmission tuning price approved.',
    ownerApproval: 'Matt supplied service inclusions, engine ECU scope, labour and scan rates, entry cam guide, coding, deposit and workshop policies on 9 October 2026. He then confirmed supplementary prices plus GST, machining and fitting boundaries, LS engine eligibility, DOD requirements, lubrication and the full service report. He subsequently confirmed the full cam inclusions, head removal and lifter package, additional L77 and L76 DOD cost, and fully electric servicing from AUD $325 including GST. Exact job scope still needs PSI confirmation.',
    consumerRights: 'ACCC consumer rights and guarantees guidance, checked 9 October 2026. Workmanship and applicable consumer guarantees cannot be removed by a blanket policy.',
    plus: 'Current mobile performance-plus.tsx and public Australian App Store description',
    mail: 'Anonymised recurring enquiry topics from selected PSI Outlook correspondence, March to October 2026. No individual prices approved.',
    boundary: 'Private Boost test scope and owner instructions. No connected inbox or production actions.',
  });
  const faq = (id, category, question, reply, sources, prompts = [], links = []) => Object.freeze({ id, category, question, reply, sources, prompts, links, verifiedOn: VERIFIED_ON });
  const FAQS = Object.freeze([
    faq('download', 'App', 'Where can I download the PSI app?', 'Download PSI Performance Garage for iPhone or Android. The app is the easiest way to keep your vehicles and booking requests together. Which phone do you use?', ['stores','booking'], ['I use an iPhone', 'I use Android', 'I already have the app'], ['apple','android']),
    faq('iphone', 'App', 'I use an iPhone', 'Open the iPhone App Store link, tap Get and open PSI Performance Garage. If it is already installed, tap Open. Next, sign in with your email code.', ['stores','account'], ['How do I create an account?', 'I already have an account'], ['apple']),
    faq('android', 'App', 'I use Android', 'Open the Google Play link, tap Install and open PSI Performance Garage. Use the same PSI email if you already have an account. Next, request your email sign in code.', ['stores','account'], ['How do I create an account?', 'I already have an account'], ['android']),
    faq('installed', 'App', 'I already have the app', 'Great. Sign in with your PSI email, then use Book ahead in Bookings. Choose Service & Report or Dyno Tuning and select your saved vehicle.', ['account','booking'], ['How do I sign in?', 'How do I book?', 'How do I add a vehicle?']),
    faq('signup', 'App', 'How do I create an account?', '1. Open PSI Performance Garage and the Account screen.\n2. Enter your email and tap Email my sign-in code.\n3. Enter the six digit email code and tap Verify and sign in.\n4. Add your name, mobile and vehicle details.\n5. Tap Save account details.\nNo password or paid subscription is needed to create your account.', ['account','plus'], ['Guide me through account setup', 'My code has not arrived', 'How do I book?']),
    faq('signin', 'App', 'How do I sign in?', 'Use the email already linked to your PSI account. Tap Email my sign-in code, enter the newest six digit code from your email, then tap Verify and sign in. No password is required.', ['account'], ['My code has not arrived', 'I forgot my password', 'How do I book?']),
    faq('password', 'App', 'I forgot my password', 'PSI uses an email code, so there is no PSI password to reset. Enter your account email and tap Email my sign-in code. Never send that code to Boost or anyone else.', ['account'], ['My code has not arrived', 'I cannot access my email']),
    faq('code-help', 'App', 'My code has not arrived', 'Check the email spelling and your junk folder. Wait for the resend timer, then use Request a new code. Enter only the newest code within 10 minutes. If it still fails, choose Message PSI. Do not share the code here.', ['account'], ['Message PSI', 'How do I create an account?']),
    faq('garage', 'App', 'How do I add a vehicle?', 'Finish your account profile with your mobile, vehicle registration, year, make and model. Save account details, then open My Garage. Use Add vehicle for another car. If PSI created a vehicle record, ask PSI to correct its verified details.', ['account','garage'], ['How do I book?', 'My vehicle record is missing']),
    faq('free', 'App', 'Is the app free?', 'Yes. Downloading the app, your profile, My Garage, enquiries and booking requests are free. Performance+ is optional for the fuller private workshop record and file archive. Workshop work is charged separately.', ['stores','plus'], ['What is Performance+?', 'How do I book?'], ['apple','android']),
    faq('plus', 'App', 'What is Performance+?', 'Performance+ opens the fuller private vehicle record, including available workshop photos, invoice copies, dyno files and supporting documents. It covers the vehicles in your PSI account. Only records PSI has published for your car appear.', ['plus'], ['What does Performance+ cost?', 'Is the app free?', 'How does the trial work?']),
    faq('plus-price', 'App', 'What does Performance+ cost?', 'The Australian guide is AUD $9.99 monthly or AUD $99.00 annually. Open Performance+ in the app to see the current store price and terms before choosing. It is optional and does not pay for servicing or workshop deposits.', ['plus','stores'], ['How does the trial work?', 'Is the app free?']),
    faq('trial', 'App', 'How does the trial work?', 'Completing your own verified PSI account starts one complimentary 14 day Performance+ trial. It takes no payment and does not renew automatically. After it ends, PSI Free remains available. Your app shows your own access status.', ['plus'], ['Is the app free?', 'What is Performance+?']),
    faq('restore', 'App', 'How do I restore Performance+?', 'Sign in to your existing PSI account, open Performance+ and choose Restore purchases using the store account that made the purchase. If access is still missing, choose Message PSI. Do not buy it again just to troubleshoot.', ['plus'], ['Message PSI']),
    faq('subscription-manage', 'App', 'How do I manage my subscription?', 'Open Performance+ and use Manage Apple subscription or Manage Google Play subscription for the store that billed you. The store shows your renewal and cancellation options. Boost cannot change or refund a subscription.', ['plus'], ['How do I restore Performance+?', 'Message PSI']),
    faq('records-guide', 'App', 'Where do I find workshop records?', 'Sign in and select the correct vehicle in My Garage or Reports. Available PSI records appear against that vehicle. Detailed files and the full archive use Performance+ access. If something is missing, PSI must check the account and vehicle match.', ['plus','garage'], ['My vehicle record is missing', 'What is Performance+?']),
    faq('booking', 'Booking', 'How do I book?', 'The free PSI app keeps your vehicles and booking requests together. Download it below if needed.\n1. Sign in and save your vehicle.\n2. Open Bookings, then Book ahead.\n3. Choose Service & Report or Dyno Tuning, then your vehicle.\n4. Complete the job, setup, contact and timing steps.\n5. Review and tap Submit request for PSI review.\nPSI confirms the scope and date. Prefer the website? Use Website enquiry.', ['booking','account','stores'], ['Guide me through a booking', 'I need the app', 'Website enquiry'], ['apple','android','enquiry']),
    faq('website-enquiry', 'Booking', 'Can I enquire without the app?', 'Yes. Use Book an appointment on the PSI website. Choose General Enquiry / Service Booking, Dyno Tuning or Plan Builder, add your car and contact details, then Send enquiry. It is a request for PSI review, not a confirmed date or payment.', ['website'], ['How do I book in the app?', 'What is Plan Builder?'], ['enquiry']),
    faq('booking-choice', 'Booking', 'Which booking option should I choose?', 'Choose Service & Report for servicing, diagnostics, repairs or EV and hybrid checks. Choose Dyno Tuning for calibration and measured performance work. For a larger build idea, use Plan Builder in the website enquiry form.', ['booking','website'], ['How do I book?', 'What is Plan Builder?']),
    faq('confirmed', 'Booking', 'Is submitting a request a confirmed booking?', 'No. PSI reviews your request and preferred date first. Follow the approved booking instructions and any deposit request. The app shows the booking status after PSI verifies the required deposit.', ['booking'], ['How do deposits work?', 'How do I book?']),
    faq('deposit', 'Booking', 'How do deposits work?', 'Minimum deposits are AUD $100 for Service & Report and AUD $300 for Dyno Tuning to reserve the hoist or dyno for the agreed day. No payment is taken on enquiry. After PSI approves the date, follow your booking’s deposit instructions. PSI must verify the deposit before confirming it.', ['booking','ownerApproval'], ['What is your cancellation policy?', 'What is your date change policy?', 'Message PSI']),
    faq('cancellation-policy', 'Booking', 'What is your cancellation policy?', 'PSI’s standard policy is to retain the deposit if you cancel. Any applicable consumer rights and the circumstances still need to be considered. Contact PSI to review a cancellation or refund request. Boost cannot decide a refund or cancel a booking.', ['ownerApproval','consumerRights'], ['What is your date change policy?', 'Message PSI']),
    faq('reschedule-policy', 'Booking', 'What is your date change policy?', 'Contact PSI early if you need a different date. With timely communication and PSI’s agreement, your deposit can move to a future booking instead of paying another deposit. PSI must confirm the new date and transfer. Boost cannot change the booking.', ['ownerApproval'], ['Message PSI']),
    faq('payment', 'Booking', 'How do I pay for workshop work?', 'Use the payment instructions on your actual PSI booking or Xero invoice. Workshop payments are separate from Performance+ subscriptions. Boost cannot take card details, verify a transfer or mark an invoice paid.', ['booking','plus','boundary'], ['How do deposits work?', 'Message PSI']),
    faq('availability', 'Booking', 'What is your next available appointment?', 'PSI needs to confirm current availability. In the app, choose your preferred date or I’m flexible and submit the request. For an urgent enquiry, call 0433 431 781.', ['booking','website'], ['How do I book?', 'Website enquiry']),
    faq('arrival', 'Booking', 'Can I drop off outside normal hours?', 'The app lets you request an arrival arrangement, including before or after hours. PSI must agree to it first. Ask PSI for the approved drop off instructions rather than leaving the car or keys unarranged.', ['booking'], ['How do I book?', 'Message PSI']),
    faq('turnaround', 'Booking', 'How long will the work take?', 'That depends on the job, diagnosis and parts availability. PSI confirms timing after reviewing your car and scope. Include when you need the car back in your request. Boost cannot promise a same day finish.', ['workshop','mail'], ['How do I book?', 'Website enquiry']),
    faq('plan', 'Workshop', 'What is Plan Builder?', 'It is the website enquiry path for a build or upgrade idea. Select the areas you want to discuss, then your intended use, priority, timing, budget direction and current setup. PSI reviews the combination before recommending parts or quoting.', ['website'], ['Website enquiry', 'Do you build engines?'], ['enquiry']),
    faq('service', 'Workshop', 'What does Service & Report cover?', 'From AUD $423.50 including GST, subject to your vehicle and required work. Routine engine servicing includes engine oil, oil filter and sump plug washer replacement, necessary fluid top ups, tyre pressures including the spare, wheel nut torque checks, and lubrication of door, bonnet and boot hinges and latches where applicable. A full vehicle check and report identifies damage and mechanical work needing attention. Extras are reported, quoted and approved before proceeding.', ['booking','ownerApproval','pricingApproval'], ['What is in the service report?', 'Does a service include spark plugs?', 'How do I book?']),
    faq('service-inclusions', 'Workshop', 'Does a service include spark plugs?', 'Routine engine service inclusions cover oil, oil filter and sump plug washer replacement, fluid top ups, tyre pressures including the spare, wheel nut torque, applicable hinge and latch lubrication, and a full vehicle check and report. Spark plugs, other filters, complete fluid changes and repairs are not automatically included. PSI reports and quotes extras for your approval before proceeding. EV and hybrid scope needs model confirmation.', ['ownerApproval','ev'], ['What is in the service report?', 'What does servicing cost?', 'How do I book?']),
    faq('service-report', 'Workshop', 'What is in the service report?', 'The service includes a full vehicle check and report covering fluids, damage found and mechanical issues needing attention. PSI also checks wheel nut torque and tyre pressures, including the spare, and lubricates door, bonnet and boot hinges and latches where applicable. Recommended extra work is reported and quoted for your approval before proceeding.', ['ownerApproval'], ['What does Service & Report cover?', 'Will you ask before doing extra work?']),
    faq('logbook', 'Workshop', 'Do you do logbook servicing?', 'Yes. PSI offers logbook and routine servicing. Include your make, model, year, kilometres and the service due so PSI can confirm the correct scope. Use Service & Report in the app.', ['workshop','mail','booking'], ['How do I book?', 'What does servicing cost?']),
    faq('diagnostics', 'Workshop', 'Can you diagnose a warning light or fault?', 'Yes. Describe the symptom, when it happens and what has already been checked or replaced. PSI inspects and tests before recommending repairs. Book Service & Report and select diagnostics. Boost cannot diagnose the cause from chat.', ['workshop','booking','mail'], ['How do I book?', 'I need a quote']),
    faq('scan-price', 'Workshop', 'What does a diagnostic scan cost?', 'A vehicle diagnostic scan costs AUD $88 including GST. This covers use of the diagnostic equipment and relevant software. It is not a fixed price for all fault finding or repairs. Further investigation and work are quoted for approval.', ['ownerApproval'], ['What is your hourly labour rate?', 'How do I book?']),
    faq('labour-rate', 'Workshop', 'What is your hourly labour rate?', 'Labour is AUD $187 per hour including GST. PSI has no minimum labour charge. The job scope and time needed determine the total, with extra work quoted for approval. A diagnostic scan is a separate AUD $88 including GST.', ['ownerApproval'], ['What does a diagnostic scan cost?', 'I need a quote']),
    faq('extra-work', 'Workshop', 'Will you ask before doing extra work?', 'Yes. When your vehicle is here, PSI inspects it. If we find a concern or recommend additional work, we notify you, explain the work and quote the price. We get your approval before commencing additional repairs. The starting package or service price does not authorise extra repairs, parts or upgrades.', ['ownerApproval'], ['What does Service & Report cover?', 'Message PSI']),
    faq('brakes', 'Workshop', 'Do you do brakes and suspension?', 'Yes. PSI offers brake, steering and suspension work, including fault checks and wheel alignment. Tell us the car and whether you want a repair or upgrade. PSI confirms the suitable parts and scope.', ['workshop','ev','website'], ['How do I book?', 'I need a quote']),
    faq('cooling', 'Workshop', 'Do you check cooling systems?', 'Yes. Cooling concerns can be selected in Service & Report. Include the car and symptoms. EV and hybrid enquiries can include battery, inverter and motor cooling, subject to the vehicle and supported work.', ['ev','booking'], ['How do I book?', 'Do you service electric cars?']),
    faq('engine-build', 'Workshop', 'Do you build engines?', 'Yes. PSI offers engine builds, rebuilds and head and cam work. The plan depends on engine condition, supporting parts, fuel and intended use. Use website Plan Builder for a build proposal, or Service & Report for a fault assessment.', ['workshop','website','mail'], ['What is Plan Builder?', 'I need a quote']),
    faq('upgrades', 'Workshop', 'What upgrades do you offer?', 'PSI can help with cam packages, intake and exhaust upgrades, turbo or supercharger projects, brakes, suspension and supported vehicle coding. Tell me your car, current setup and what you want to improve. PSI confirms suitability, quotes the scope and gets your approval before proceeding with additional work.', ['workshop','website','ownerApproval'], ['What does a cam package cost?', 'Do you supply and fit exhausts?', 'Do you do brakes and suspension?']),
    faq('cam', 'Workshop', 'Can you help choose a cam package?', PRICE_GUIDES.cam + ' Include your engine, transmission, current setup and goal so PSI can recommend a suitable combination.', ['ownerApproval'], ['What does a cam package cost?', 'What is Plan Builder?']),
    faq('cam-inclusions', 'Workshop', 'What is included in the entry cam package?', 'The standard cam package includes camshaft, valve springs, locks, retainers and stem seals; heavy duty pushrods; ARP camshaft and crankshaft bolts; timing cover and water pump gaskets; front crank seal; timing chain; coolant; labour and engine ECU dyno tuning. A three bolt camshaft gear is included where conversion from a single bolt gear is required. Lifters and cylinder head removal are extra. PSI confirms the suitable specification and any additional work.', ['ownerApproval'], ["What extra parts can a cam job need?","What does the head removal and lifter package cost?"]),
    faq('cam-options', 'Workshop', 'What extra parts can a cam job need?', 'Lifters, head gaskets and bolts, exhaust manifold gaskets, spark plugs, sump and rocker cover gaskets may be extra, depending on the job. Accessing the lifters requires cylinder head removal. PSI can quote CNC porting while the heads are off; it remains optional. L77 and L76 require the head removal, lifter package and additional DOD work for the cam upgrade. PSI quotes extras for approval.', ['ownerApproval'], ["What does the head removal and lifter package cost?","Does a cam upgrade need a DOD delete?","What does sump gasket replacement cost?"]),
    faq('sump-gasket', 'Workshop', 'What does sump gasket replacement cost?', 'Sump gasket replacement is AUD $750 including GST to supply and fit the gasket, with parts and labour included. This also includes blocking off the oil pressure relief valve where fitted. It is additional to the base cam package, not the sump plug washer changed during routine servicing. PSI confirms applicability and the agreed scope for your vehicle before proceeding.', ['ownerApproval'], ['Does that include fitting?', 'What extra parts can a cam job need?']),
    faq('lifter-package', 'Workshop', 'What does the head removal and lifter package cost?', 'During a cam job, the head removal and lifter package adds AUD $2,000 + GST, which is AUD $2,200 including GST. It includes head removal and refitting labour, genuine MLS head gaskets, LS7 lifters, LS2 lifter buckets and bolts, block cleaning and preparation, and GM head bolts. This is a parts and labour package, not labour alone. CNC porting, valve seat upgrades and other additional items are separate. L77 and L76 also need the DOD work.', ['ownerApproval'], ["Does a cam upgrade need a DOD delete?","What does CNC head porting cost?"]),
    faq('ev-service', 'EV and hybrid', 'What does fully electric servicing cost?', 'Fully electric BEV servicing starts from AUD $325 including GST. With no combustion engine, there is no engine oil or engine oil filter change. PSI confirms the service scope for your model and quotes additional work for approval. Hybrids have a combustion engine, so this BEV guide does not apply to them. This starts AUD $98.50 below the AUD $423.50 engine service guide; neither is a fixed quote for every job.', ['ownerApproval'], ["What EV work do you do?","How do I book?"]),
    faq('cam-extras', 'Workshop', 'What supporting upgrades can a cam package need?', 'CNC head porting, valve seat upgrades, and the oil pump with CHE trunnions are options across PSI’s listed LS engine combinations. Head work requires cylinder head removal and additional parts and labour. The pump and trunnion combination has no additional fitting labour when installed during the cam job. Cam specification, condition and driveline determine the complete scope. PSI inspects, quotes any additional work and gets your approval before proceeding.', ['ownerApproval'], ['What does CNC head porting cost?', 'What does a valve seat upgrade cost?', 'What does the oil pump and CHE trunnion upgrade cost?']),
    faq('cam-engines', 'Workshop', 'Which engines are the cam packages for?', 'The starting guide is for Holden and Chevrolet LS engines: LS1, LS2, LS3, LSA, L77, L76 and L98. CNC head work and the supporting upgrade options can be considered across these combinations. PSI checks your actual engine, existing modifications and driveline before confirming the package. Other engine families need an individual quote.', ['ownerApproval'], ['Does a cam upgrade need a DOD delete?', 'What does a cam package cost?']),
    faq('dod-delete', 'Workshop', 'Does a cam upgrade need a DOD delete?', 'L77 and L76 require cylinder head removal, the lifter package and DOD work with a cam upgrade. These are separately quoted requirements, not optional upgrades. LS1, LS2, LS3, L98 and LSA do not require that kit for PSI’s listed packages. PSI checks the actual engine and previous modifications and confirms the required work and price for approval before proceeding.', ['ownerApproval'], ['What do the L77 and L76 DOD extras cost?', 'Which engines are the cam packages for?']),
    faq('dod-price', 'Workshop', 'What do the L77 and L76 DOD extras cost?', 'L77 and L76 cam upgrades require the AUD $2,000 + GST head removal and lifter package, plus AUD $750 + GST for DOD work. Combined extras are AUD $2,750 + GST, which is AUD $3,025 including GST, above the base cam package. DOD work covers the valley plate, gasket and oil gallery blocking. LS1, LS2, LS3, L98 and LSA do not require that kit for PSI’s listed packages. PSI checks the actual engine and previous modifications.', ['ownerApproval'], ['What does the head removal and lifter package cost?', 'Will you ask before doing extra work?']),
    faq('cnc-heads', 'Workshop', 'What does CNC head porting cost?', 'CNC head porting is AUD $1,550 + GST, which is AUD $1,705 including GST for the porting work. This is not a complete fitted head package. Cylinder head removal and the additional parts and labour for head work cost extra. PSI confirms the full head and cam scope before proceeding.', ['ownerApproval'], ['I need a CNC head porting quote', 'What does a valve seat upgrade cost?']),
    faq('valve-seats', 'Workshop', 'What does a valve seat upgrade cost?', 'The valve seat upgrade work is AUD $750 + GST, which is AUD $825 including GST. Cylinder head removal and the additional parts and labour for the head job are extra. This is not an installed total. PSI quotes the complete scope for your engine.', ['ownerApproval'], ['I need a valve seat upgrade quote', 'What does CNC head porting cost?']),
    faq('pump-trunnions', 'Workshop', 'What does the oil pump and CHE trunnion upgrade cost?', 'The combined oil pump upgrade and CHE trunnion set is AUD $920 + GST, which is AUD $1,012 including GST. When done during the cam job, there is no additional fitting labour for this combination. It is an optional upgrade, not automatically part of the entry cam price. Standalone fitting, individual part prices and other work need a separate quote.', ['ownerApproval'], ['I need an oil pump and CHE trunnion quote', 'What supporting upgrades can a cam package need?']),
    faq('exhaust', 'Workshop', 'Do you supply and fit exhausts?', 'PSI can review exhaust supply and fitting. Specify the vehicle, engine and whether you want a rear section, full system, headers or a valved system. Fitting, tuning and any additional parts need to be included in the agreed quote.', ['website','mail'], ['I need an exhaust quote', 'Website enquiry']),
    faq('forced-induction', 'Workshop', 'Can you supply and fit a supercharger?', 'PSI can assess turbo and supercharger projects. Send the exact car, engine, current setup, fuel and intended use. Kit access, compatibility, supporting parts and tuning are confirmed individually, not assumed from the brand alone.', ['workshop','mail'], ['What is Plan Builder?', 'I need a quote']),
    faq('interchiller', 'Workshop', 'Do you fit interchillers or water meth systems?', 'PSI has handled interchiller and water meth installation enquiries. The right setup depends on the car, blower or turbo, cooling arrangement and intended use. PSI needs to confirm suitability and the complete installed scope.', ['website','mail'], ['I need a quote', 'What is Plan Builder?']),
    faq('dyno', 'Tuning', 'Do you do dyno tuning?', 'Yes. ' + PRICE_GUIDES.dyno + ' Use Dyno Tuning in the app and include your current setup and tuning goal.', ['workshop','booking','pricingApproval'], ['What details do I need for tuning?', 'How do I book?', 'What does a tune cost?']),
    faq('dyno-details', 'Tuning', 'What details do I need for tuning?', 'Include the engine and modifications, transmission, differential, injectors and pump, fuel, intake, exhaust, cam and any previous tune. If you do not know the setup, choose the PSI inspection option rather than guessing.', ['booking','website'], ['How do I book?', 'I need a quote']),
    faq('ecu-tcu', 'Tuning', 'Is transmission tuning included with an engine tune?', 'Transmission tuning costs extra. The price depends on your vehicle, transmission, setup and modifications. PSI confirms the cost before proceeding.', ['transmissionApproval'], ['I need a transmission tuning quote', 'How do I book?']),
    faq('module-tuning', 'Tuning', 'Are ECU unlocking and other modules included?', 'No universal module price applies. Some vehicles need ECU unlocking, transmission, fuel pump, CPC or other module work in addition to engine tuning. PSI prices each requirement for the vehicle, setup and supporting modifications before proceeding.', ['ownerApproval'], ['I need a module tuning quote', 'How do I book?']),
    faq('otr', 'Tuning', 'Do you supply and fit OTR intakes with a tune?', 'For Holden and HSV, supplied and fitted OTR intake and tune combinations start from AUD $1,500 + GST, which is AUD $1,650 including GST. The exact vehicle, intake, exhaust, extractors and computer determine suitability and the final price. This does not include supplying an exhaust or extractors. Other vehicles need an individual quote.', ['ownerApproval'], ['I need an OTR and tune quote', 'Website enquiry']),
    faq('power', 'Tuning', 'How much power will my car make?', 'PSI must assess the exact setup before discussing a realistic result. Fuel, condition and supporting parts matter. No power or economy gain is guaranteed by Boost. Include your goal in a Dyno Tuning request.', ['workshop','estimator','booking'], ['What details do I need for tuning?', 'How do I book?']),
    faq('estimator', 'Tuning', 'Can I use the Power Estimator as a quote?', 'No. The website currently labels the Power Estimator a development preview and says its figures are not approved for customer quotations. Use it for initial context only, then ask PSI to assess your exact setup.', ['estimator'], ['What details do I need for tuning?', 'Website enquiry']),
    faq('fuel', 'Tuning', 'Can you tune for E85 or flex fuel?', 'The enquiry form accepts 98 RON, E85, flex fuel, race fuel and other setups. PSI must check your fuel system, controller support and intended use before confirming the tuning scope. Do not change fuel on Boost’s advice.', ['booking','website'], ['What details do I need for tuning?', 'I need a quote']),
    faq('ev', 'EV and hybrid', 'Do you service electric and hybrid cars?', 'Yes. Choose Service & Report in the app, then Hybrid, Plug in Hybrid or Electric. Select the relevant service options and explain the concern. PSI confirms what is supported for your model.', ['ev','booking'], ['What EV work do you do?', 'How do I book?', 'Do you rebuild EV batteries?'], ['ev']),
    faq('ev-scope', 'EV and hybrid', 'What EV work do you do?', 'The scope includes scheduled servicing, warning light diagnostics, visual and diagnostic high voltage inspections, vehicle charging faults, 12V electrical work, cooling, brakes, suspension, tyres and alignment. PSI confirms suitability for the exact vehicle.', ['ev'], ['How do I book?', 'Do you rebuild EV batteries?']),
    faq('ev-battery', 'EV and hybrid', 'Do you rebuild EV batteries?', 'Battery pack rebuilding is not part of PSI’s current EV offering. PSI can review a battery or charging concern and explain the next step for supported diagnostics or specialist repair.', ['ev'], ['What EV work do you do?', 'Message PSI']),
    faq('ev-type', 'EV and hybrid', 'Which vehicle type do I choose?', 'Choose Petrol or Diesel for a conventional vehicle. HEV means Hybrid, PHEV means Plug in Hybrid, and BEV means fully Electric. Select the type that matches your exact car, not just its brand.', ['booking'], ['How do I book?', 'What EV work do you do?']),
    faq('charging', 'EV and hybrid', 'Can you check a charging fault?', 'PSI can investigate vehicle charging concerns, including the charge port, onboard systems and supporting 12V supply. Include the model and what happens while charging. Home charger installation is not an advertised PSI service.', ['ev'], ['How do I book?', 'I need a quote']),
    faq('coding', 'Workshop', 'Do you do vehicle coding?', 'PSI offers supported Mercedes module coding, including a remote coding dongle for interstate work. Compatibility depends on your model, year, hardware and requested feature. See the coding page for options. Other makes and features are assessed and priced individually. PSI confirms suitability and the exact total before purchase.', ['coding','ownerApproval'], ['I need a coding quote', 'Website enquiry'], ['coding']),
    faq('fitment', 'Shop', 'Will this part fit my car?', 'Send the product link or part number, vehicle year, model, engine and relevant modifications. Say whether you need supply only or supply and fitting. PSI must confirm compatibility before you order an uncertain fitment.', ['website','mail'], ['I need a parts quote', 'Website enquiry']),
    faq('stock', 'Shop', 'Is the part in stock?', 'Check the exact product and variant on the website. Boost has no live stock feed. Some items need ordering or manufacture, so PSI must confirm availability and timing before you rely on a delivery date.', ['mail','boundary'], ['Website enquiry'], ['shop']),
    faq('shipping', 'Shop', 'How much is shipping?', 'Shipping depends on the item, quantity and destination. Use the website checkout for the available options, or ask PSI about a bulky or special order. Boost cannot confirm freight or dispatch dates from an old quote.', ['website','mail'], ['Website enquiry'], ['shop']),
    faq('discount', 'Shop', 'Can you offer a discount?', 'Boost cannot issue discounts or change a quote. PSI can review the exact product or proposed work. Include the product link or your vehicle and scope in the website enquiry.', ['boundary','mail'], ['Website enquiry']),
    faq('location', 'Contact', 'Where are you?', 'PSI is at 21 Exchange Drive, Pakenham VIC 3810. Call 0433 431 781 or email info@psiperformance.com.au.', ['website'], ['What are your hours?', 'How do I book?']),
    faq('hours', 'Contact', 'What are your hours?', 'Published workshop hours are Monday to Friday, 8:30 am to 5 pm. Saturday is by appointment. Confirm holiday hours and special arrangements directly with PSI.', ['website'], ['Where are you?', 'How do I book?']),
    faq('contact', 'Contact', 'How can I contact PSI?', 'Call 0433 431 781 or email info@psiperformance.com.au. You can also send a website enquiry. Message PSI here currently opens only Matt’s local test inbox; it does not send a real message.', ['website','boundary'], ['Message PSI', 'Website enquiry'], ['enquiry']),
    faq('bot', 'About Boost', 'Are you a real person?', 'I’m Boost, PSI’s test assistant. I can explain verified information and help prepare an enquiry. I cannot inspect your car or access your account. Message PSI hands this conversation to the simulated inbox in this private preview.', ['boundary'], ['How do I book?', 'Message PSI']),
    faq('loan-car', 'Booking', 'Do you have a loan car or pickup service?', 'PSI does not offer loan cars. Towing, pickup and vehicle transport are arranged between you and your transport provider. Confirm workshop arrival arrangements with PSI before organising delivery.', ['ownerApproval'], ['Website enquiry', 'Message PSI']),
    faq('warranty', 'Workshop', 'Will modifications affect my warranty or road compliance?', 'PSI needs to review the vehicle, proposed work and any relevant requirements. Boost cannot promise warranty coverage, road legality or engineering approval. Ask for the scope and any required checks before proceeding.', ['boundary'], ['Website enquiry', 'Message PSI']),
    faq('workmanship', 'Workshop', 'Do you offer a workmanship warranty?', 'PSI offers a workmanship warranty. Modified engine warranty scope is limited and needs to be confirmed in writing for the job. Parts cover varies with the item and supplier. Your applicable rights under Australian Consumer Law still apply. Report a fault to PSI for assessment; Boost cannot accept or reject a warranty claim.', ['ownerApproval','consumerRights'], ['Can I bring my own parts?', 'Message PSI']),
    faq('quote-validity', 'Quotes', 'Can I use an old quote?', 'PSI quotes are generally valid for 7 to 14 days at most. Use the expiry shown on your written quote and ask PSI to recheck it if expired. Supplier prices, parts availability and exchange rates for imported items can change. Boost cannot extend a quote or change an agreed price.', ['ownerApproval'], ['I need a quote', 'Website enquiry']),
    faq('included-work', 'Quotes', 'Does that include fitting and tuning?', 'The written quote needs to list parts, fitting, tuning and any extra work separately or clearly include them in the package. PSI must confirm your exact scope before you proceed.', ['mail'], ['I need a quote', 'Website enquiry']),
    faq('own-parts', 'Quotes', 'Can I bring my own parts?', 'Ask PSI before buying or bringing parts. Supply the receipt, part details and any inspection paperwork so PSI can assess suitability and safety. You are responsible for sourcing customer supplied parts; PSI does not provide the supplier’s parts warranty. PSI’s workmanship obligations and applicable consumer rights still apply. Any failure needs assessment, not an automatic denial.', ['ownerApproval','consumerRights'], ['Do you offer a workmanship warranty?', 'Website enquiry']),
    faq('send-photos', 'About Boost', 'Can I send a photo here?', 'This preview accepts text only. Describe the issue or part and mention that photos are available. Do not paste sign in codes, bank details or private account documents into the test.', ['boundary'], ['Message PSI']),
    faq('message-delivery', 'About Boost', 'Does Matt receive these test messages?', 'Only in Matt’s test inbox inside this preview. Nothing is delivered to Shopify Inbox, email, SMS or the PSI app yet. Switch to Matt’s test inbox to rehearse a reply and read times.', ['boundary'], ['Message PSI']),
  ]);
  const BY_ID = Object.freeze(Object.fromEntries(FAQS.map(item => [item.id, item])));
  // Rules are intentionally explicit. Questions needing private access or safety
  // assessment are intercepted by the engine before this public FAQ layer.
  const RULES = [
    ['message-delivery', /\b(test messages|receive.*messages|send.*(?:email|sms|whatsapp|shopify inbox))\b/],
    ['send-photos', /\b(send|upload|attach)\b.*\b(photo|picture|image|file)\b/],
    ['quote-validity', /\b(old quote|previous quote|quote.*valid|quotes.*valid|quote.*expir|honour.*quote|honor.*quote)\b/],
    ['cancellation-policy', /\b(cancellation policy|cancellation terms)\b|^(?:are|is) (?:the |your |booking )?deposits? (?:non )?refundable$/],
    ['reschedule-policy', /\b(date change policy|rescheduling policy|reschedule policy|deposit transfer policy)\b|^can (?:a|the) deposit (?:be )?(?:move|moved|transfer|transferred)\b/],
    ['own-parts', /\b(own parts|bring.*parts|supplied parts)\b/],
    ['workmanship', /\b(workmanship|your warranty|psi warranty|parts warranty|modified engine warranty)\b/],
    ['scan-price', /\b(diagnostic scan|diagnostic scans|scan tool|code scan|fault code scan|scan fee|scan cost|scan price|scanning)\b|\b(scan)\b.*\b(cost|price|charge)\b|\b(cost|price|charge|how much)\b.*\b(scan)\b/],
    ['labour-rate', /\b(hourly|labour rate|labor rate|labour cost|labor cost|minimum charge|minimum labour|minimum labor|per hour)\b/],
    ['extra-work', /\b(extra work|additional work|extra repairs)\b.*\b(approv\w*|ask|permission|agree\w*)\b|\b(approv\w*|ask|permission|agree\w*)\b.*\b(extra work|additional work|extra repairs)\b/],
    ['module-tuning', /\b(cpc|unlock\w*|fuel pump module|other modules|module tuning)\b/],
    ['sump-gasket', /\b(sump gasket|oil pan gasket|oil pressure relief valve)\b/],
    ['cam-inclusions', /\b(cam|camshaft)\b.*\b(include\w*|contents|comes with|cover\w*)\b|\b(include\w*|contents|comes with|cover\w*)\b.*\b(cam|camshaft)\b/],
    ['lifter-package', /\b(head removal|remove.*heads?|heads?.*remov|lifter package|lifter kit|ls7 lifters|ls2 lifter buckets)\b/],
    ['cam-options', /\b(cam|camshaft)\b.*\b(optional|extra parts|additional parts)\b/],
    ['ev-service', /\b(fully electric|full electric|electric vehicle|electric car|bev)\b.*\b(service|servicing|maintenance|oil|filter)\b|\b(service|servicing|maintenance|oil|filter)\b.*\b(fully electric|full electric|electric vehicle|electric car|bev)\b/],
    ['included-work', /\b(include|included|includes)\b.*\b(fitting|installation|tuning|tune|labour|labor|gst)\b/],
    ['password', /\b(password|forgot.*password|reset.*password)\b/],
    ['code-help', /\b(code|codes|email)\b.*\b(arriv|arrived|not received|didnt|hasnt|not working|expired|invalid|resend|spam|junk)\b|\b(no code|missing code|resend|cant log in|cant sign in|cannot log in|cannot sign in)\b/],
    ['subscription-manage', /\b(cancel|manage|stop|renewal|renew)\b.*\b(subscription|performance plus|performance)\b|\bsubscription\b.*\b(cancel|manage|renewal)\b/],
    ['restore', /\b(restore purchases|restore performance|already paid.*performance|paid twice|subscription.*missing)\b/],
    ['trial', /\b(trial|fourteen days|14 day)\b/],
    ['plus-price', /\b(performance plus|performance|subscription)\b.*\b(price|cost|much|monthly|annual)\b|\b(price|cost|much)\b.*\b(performance|subscription)\b/],
    ['free', /\b(how much|cost|price)\b.*\b(app|download|create.*account)\b|\b(app|download)\b.*\b(cost|price)\b/],
    ['free', /\b(app|booking|bookings|account|enquir\w*)\b.*\b(free|pay|paid|subscription required)\b|\b(free app|free account|pay to book|pay for.*app|need.*performance.*book)\b/],
    ['plus', /\b(performance plus|performance membership|subscription benefits)\b|^what is performance$/],
    ['website-enquiry', /\b(website enquiry|website form|enquiry form|without (?:the )?app|dont want.*app|no app|app required|do i need (?:the )?app|have to.*app|must.*app)\b|\b(book|enquire|enquiry)\b.*\b(website|online|browser)\b/],
    ['code-help', /\b(code)\b.*\b(not|wrong|failed)\b/],
    ['signup', /\b(create|make|register|set up|setup|new)\b.*\b(account|profile)\b|\b(sign up|signup|register|account setup)\b/],
    ['signin', /\b(sign in|signin|log in|login|existing account|already have an account)\b/],
    ['garage', /\b(add|save)\b.*\b(car|vehicle)\b|\b(my garage|multiple cars|another car|second car)\b/],
    ['records-guide', /\b(where|how)\b.*\b(find|see|view|open)\b.*\b(invoice|records|photos|dyno files|history)\b/],
    ['installed', /\b(already|installed|downloaded)\b.*\b(app)\b|\b(app)\b.*\b(installed|downloaded)\b/],
    ['iphone', /^(?:i (?:use|have|am on|have an?) |im on |on |an? )?(?:apple|iphone|ios)(?: phone)?$/],
    ['android', /^(?:i (?:use|have|am on|have an?) |im on |on |an? )?(?:android|samsung|google pixel)(?: phone)?$/],
    ['iphone', /\b(iphone|ios|apple)\b.*\b(download|install|get the app)\b|\b(download|install)\b.*\b(iphone|ios|apple)\b/],
    ['android', /\b(android|samsung|google play)\b.*\b(download|install|get the app)\b|\b(download|install)\b.*\b(android|samsung|google play)\b/],
    ['download', /\b(download|install|app store|google play|get the app|need the app)\b/],
    ['booking-choice', /\b(which|what)\b.*\b(booking option|booking type|choose.*book|book.*choose)\b/],
    ['ev-type', /\b(which|what)\b.*\b(powertrain|vehicle type|hev|phev|bev)\b|\b(hev|phev|bev)\b.*\b(mean|difference)\b/],
    ['confirmed', /\b(submit|submitting|request)\b.*\b(confirm|confirmed|reserve|reserved)\b|\b(how|when)\b.*\b(booking)\b.*\b(confirmed)\b/],
    ['deposit', /\b(deposit|deposits)\b/],
    ['payment', /\b(how|can|where|do)\b.*\b(pay|payment|card|cash|bank transfer|stripe|eftpos|afterpay|payright)\b/],
    ['arrival', /\b(drop off|dropoff|after hours|before hours|keys)\b/],
    ['availability', /\b(availability|available|earliest|next appointment|next booking|slot)\b/],
    ['turnaround', /\b(how long|turnaround|same day|while i wait|car back|finish time)\b/],
    ['loan-car', /\b(loan car|courtesy car|pickup|pick up|tow|towing|transport)\b/],
    ['warranty', /\b(warranty|legal|legality|roadworthy|road compliance|engineer|engineering|certified)\b/],
    ['estimator', /\b(power estimator|estimator|stage [1234])\b/],
    ['ecu-tcu', /\b(tcu|tcm|transmission tun\w*|gearbox tun\w*)\b/],
    ['fuel', /\b(e85|flex fuel|race fuel|98 ron)\b/],
    ['power', /\b(power gain|horsepower|how much power|how many kw|fuel economy|fuel efficiency)\b/],
    ['dyno-details', /\b(need|details|prepare|preparation|setup)\b.*\b(dyno|tuning|tune)\b|\b(dyno|tuning)\b.*\b(need|details|prepare|setup)\b/],
    ['ev-battery', /\b(battery pack|ev battery|ev batteries|traction battery)\b.*\b(rebuild\w*|repair|replace)\b|\b(rebuild\w*|repair)\b.*\b(ev batter\w*|battery pack)\b/],
    ['ev-scope', /\b(ev|electric|hybrid)\b.*\b(work|include|scope|options)\b|\b(what work|what services|what checks)\b.*\b(ev|electric|hybrid)\b|\b(high voltage inspection|12v)\b/],
    ['charging', /\b(charging|charge port|home charger|charger install)\b/],
    ['coding', /\b(coding|code a feature|mbux|carplay|android auto|ambient lighting)\b/],
    ['fitment', /\b(fit my|fit this|will.*fit|compatible|compatibility|part number|supply only|own parts)\b/],
    ['stock', /\b(in stock|stock availability|availability of.*part|dispatch)\b/],
    ['shipping', /\b(shipping|freight|postage|delivery)\b/],
    ['discount', /\b(discount|coupon|promo code|cheaper|price match)\b/],
    ['plan', /\b(plan builder|plan a build|build plan|staged build)\b/],
    ['service-report', /\b(service report|report.*service|wheel nut|hinges?|latches|lubricat\w*)\b/],
    ['service-inclusions', /\b(include|inclusions|included)\b.*\b(plugs|filters|fluids|oil|repairs|service)\b|\b(service)\b.*\b(include|included|inclusions)\b/],
    ['logbook', /\b(logbook|log book|scheduled maintenance)\b/],
    ['diagnostics', /\b(diagnos\w*|warning light|fault|misfire|stalls|stalling|wont start|not starting)\b/],
    ['brakes', /\b(brakes|suspension|alignment|coilovers|coil overs|tyres|steering)\b/],
    ['cooling', /\b(cooling|radiator|coolant)\b/],
    ['engine-build', /\b(engine builds?|engine rebuilds?|build engines|rebuild.*engine|stroker|built motor)\b/],
    ['cam-engines', /\b(which|what)\b.*\b(engines?|cars?|vehicles?)\b.*\b(cam|package)\b|\b(cam|package)\b.*\b(which|what) engines?\b/],
    ['cam-extras', /\b(cam.*(?:supporting|extra)|(?:supporting|extra).*cam)\b/],
    ['cnc-heads', /\b(cnc|head porting|port.*heads?)\b/],
    ['valve-seats', /\bvalve seats?\b/],
    ['pump-trunnions', /\b(oil pump|che trunnion\w*|trunnions?)\b/],
    ['dod-delete', /\b(dod|afm|displacement on demand)\b/],
    ['cam', /\b(cam|camshaft|lifters|dod|afm|trunnion)\b/],
    ['interchiller', /\b(interchiller|water meth|water methanol|heat soak)\b/],
    ['forced-induction', /\b(supercharg\w*|turbo kit|turbo upgrade|forced induction|harrop|whipple)\b/],
    ['otr', /\botr\b/],
    ['exhaust', /\b(exhaust|headers|extractors|varex|cat back|downpipe|intake)\b/],
    ['upgrades', /\b(upgrades?|modifications|mods)\b/],
    ['hours', /\b(hours|opening|closing|saturday|weekend|sunday|holiday)\b|\b(are you open|when.*open|when.*close|what time)\b/],
    ['contact', /\b(contact|phone number|email address|telephone)\b/],
    ['location', /\b(address|location|where are you|where is psi|pakenham)\b/],
    ['bot', /\b(real person|are you.*bot|who are you|what can you do)\b/],
  ];
  function normalise(value) {
    return value.toLowerCase().replace(/performance\s*\+/g, 'performance plus').replace(/[’']/g, '')
      .replace(/\bdo not\b/g, 'dont').replace(/\b(servce|sevice|servicingg)\b/g, 'service')
      .replace(/\b(tunning|tuneing)\b/g, 'tuning').replace(/\b(transmision|transmisson)\b/g, 'transmission')
      .replace(/\b(u)\b/g, 'you').replace(/\b(ur)\b/g, 'your')
      .replace(/[^a-z0-9/\s]/g, ' ').replace(/\s+/g, ' ').trim();
  }
  function isPricing(q) {
    return /\b(price|prices|cost|costs|how much|quote|estimate|ballpark|ball park|pricing|package total|installed total|fitted total)\b/.test(q) && !/\b(how much power|how much horsepower)\b/.test(q);
  }
  function match(q) {
    // Workshop price questions keep scoped quote collection. Approved category
    // starting guides do not approve specific package prices or inclusions.
    const exact = FAQS.find(item => normalise(item.question) === q);
    if (exact) return exact;
    const pricing = isPricing(q);
    for (const [id, pattern] of RULES) {
      if (pricing && !['plus-price','plus','free','deposit','payment','shipping','discount','estimator','quote-validity','included-work','ev-battery','scan-price','labour-rate','cancellation-policy','reschedule-policy','extra-work','own-parts','workmanship'].includes(id)) continue;
      if (pattern.test(q)) return BY_ID[id];
    }
    if (pricing) return null;
    if (/\b(book|booking|appointment|enquire|enquiry)\b/.test(q)) return BY_ID.booking;
    if (/\b(ev|electric|hybrid|hev|phev|bev|tesla|byd|polestar)\b/.test(q)) return BY_ID.ev;
    if (/\b(dyno|tuning|tune)\b/.test(q)) return BY_ID.dyno;
    if (/\b(service|servicing|maintenance|inspection)\b/.test(q)) return BY_ID.service;
    if (/^where\b/.test(q)) return BY_ID.location;
    return null;
  }
  const api = Object.freeze({ VERIFIED_ON, PRICE_GUIDES, LINKS, SOURCES, FAQS, BY_ID, normalise, isPricing, match });
  if (typeof module === 'object' && module.exports) module.exports = api;
  else root.BoostKnowledge = api;
})(typeof window === 'object' ? window : globalThis);
