/** One SQLite statement per item; required by D1's prepared-statement API. */
export const APPROVAL_FIRST_SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS customer_profiles (
    id TEXT PRIMARY KEY NOT NULL,
    account_user_id TEXT,
    account_state TEXT NOT NULL DEFAULT 'unclaimed' CHECK (account_state IN ('unclaimed', 'active', 'disabled')),
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    mobile TEXT NOT NULL,
    contact_consent INTEGER NOT NULL DEFAULT 1 CHECK (contact_consent IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_profiles_email ON customer_profiles (email)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_profiles_account_user_id ON customer_profiles (account_user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_profiles_mobile ON customer_profiles (mobile)`,
  `CREATE TABLE IF NOT EXISTS customer_vehicles (
    id TEXT PRIMARY KEY NOT NULL,
    customer_profile_id TEXT NOT NULL,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    year INTEGER NOT NULL CHECK (year BETWEEN 1900 AND 2200),
    registration TEXT NOT NULL,
    vin TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_customer_vehicles_profile_registration ON customer_vehicles (customer_profile_id, registration)`,
  `CREATE INDEX IF NOT EXISTS idx_customer_vehicles_profile_updated ON customer_vehicles (customer_profile_id, updated_at)`,
  `CREATE TABLE IF NOT EXISTS booking_requests (
    id TEXT PRIMARY KEY NOT NULL,
    public_reference TEXT NOT NULL,
    customer_profile_id TEXT,
    vehicle_id TEXT,
    first_name_snapshot TEXT NOT NULL,
    last_name_snapshot TEXT NOT NULL,
    email_snapshot TEXT NOT NULL,
    mobile_snapshot TEXT NOT NULL,
    vehicle_make_snapshot TEXT NOT NULL,
    vehicle_model_snapshot TEXT NOT NULL,
    vehicle_year_snapshot INTEGER NOT NULL,
    registration_snapshot TEXT NOT NULL,
    vin_snapshot TEXT NOT NULL DEFAULT '',
    booking_type TEXT NOT NULL CHECK (booking_type IN ('service', 'dyno')),
    service_option TEXT NOT NULL,
    appointment_preference_mode TEXT NOT NULL,
    preferred_date TEXT,
    arrival_arrangement TEXT NOT NULL CHECK (arrival_arrangement IN ('business_hours', 'before_hours_drop_off', 'after_hours_drop_off', 'flexible')),
    after_hours_collection INTEGER NOT NULL DEFAULT 0,
    notify_earlier_availability INTEGER NOT NULL DEFAULT 0,
    service_reminder_consent INTEGER NOT NULL DEFAULT 0,
    request_details TEXT NOT NULL,
    setup_confidence TEXT,
    tuning_details_json TEXT CHECK (tuning_details_json IS NULL OR json_valid(tuning_details_json)),
    source TEXT NOT NULL CHECK (source IN ('web', 'mobile')),
    contact_consent INTEGER NOT NULL CHECK (contact_consent = 1),
    booking_terms_accepted INTEGER NOT NULL CHECK (booking_terms_accepted = 1),
    booking_policy_version TEXT NOT NULL,
    deposit_policy_version TEXT NOT NULL,
    deposit_amount_cents INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'AUD' CHECK (currency = 'AUD'),
    state TEXT NOT NULL DEFAULT 'pending_staff_review' CHECK (state IN ('pending_staff_review', 'date_proposed', 'date_approved', 'awaiting_deposit', 'confirmed', 'completed', 'cancelled')),
    state_version INTEGER NOT NULL DEFAULT 0 CHECK (state_version >= 0),
    proposed_date TEXT,
    confirmed_date TEXT,
    confirmed_arrival_arrangement TEXT CHECK (confirmed_arrival_arrangement IS NULL OR confirmed_arrival_arrangement IN ('business_hours', 'before_hours_drop_off', 'after_hours_drop_off', 'flexible')),
    confirmed_allocation_mode TEXT,
    confirmed_start_time TEXT,
    confirmed_end_time TEXT,
    staff_notes TEXT NOT NULL DEFAULT '',
    checkout_id TEXT,
    deposit_payment_id TEXT,
    completed_at TEXT,
    cancelled_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((appointment_preference_mode = 'specific' AND preferred_date IS NOT NULL) OR (appointment_preference_mode = 'flexible' AND preferred_date IS NULL)),
    CHECK ((booking_type = 'service' AND service_option = 'service_report') OR (booking_type = 'dyno' AND service_option = 'dyno_tuning')),
    CHECK ((booking_type = 'service' AND setup_confidence IS NULL AND tuning_details_json IS NULL) OR (booking_type = 'dyno' AND setup_confidence IN ('known', 'psi_inspection'))),
    CHECK (after_hours_collection IN (0, 1) AND notify_earlier_availability IN (0, 1) AND service_reminder_consent IN (0, 1)),
    CHECK ((booking_type = 'service' AND deposit_amount_cents = 10000) OR (booking_type = 'dyno' AND deposit_amount_cents = 30000)),
    CHECK ((confirmed_allocation_mode IS NULL AND confirmed_start_time IS NULL AND confirmed_end_time IS NULL) OR (confirmed_allocation_mode = 'all_day' AND confirmed_start_time IS NULL AND confirmed_end_time IS NULL) OR (confirmed_allocation_mode = 'timed' AND confirmed_start_time GLOB '[0-2][0-9]:[0-5][0-9]' AND substr(confirmed_start_time, 1, 2) BETWEEN '00' AND '23' AND confirmed_end_time GLOB '[0-2][0-9]:[0-5][0-9]' AND substr(confirmed_end_time, 1, 2) BETWEEN '00' AND '23' AND confirmed_start_time < confirmed_end_time))
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_requests_public_reference ON booking_requests (public_reference)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_requests_checkout_id ON booking_requests (checkout_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_requests_deposit_payment_id ON booking_requests (deposit_payment_id)`,
  `CREATE INDEX IF NOT EXISTS idx_booking_requests_state_created ON booking_requests (state, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_booking_requests_customer_created ON booking_requests (customer_profile_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_booking_requests_vehicle_created ON booking_requests (vehicle_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_booking_requests_confirmed_date ON booking_requests (confirmed_date)`,
  `CREATE INDEX IF NOT EXISTS idx_booking_requests_earlier_candidate ON booking_requests (notify_earlier_availability, state, preferred_date)`,
  `CREATE TABLE IF NOT EXISTS booking_request_idempotency_keys (
    key_hash TEXT PRIMARY KEY NOT NULL CHECK (length(key_hash) = 64),
    request_hash TEXT NOT NULL CHECK (length(request_hash) = 64),
    booking_request_id TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_idempotency_request_id ON booking_request_idempotency_keys (booking_request_id)`,
  `CREATE TABLE IF NOT EXISTS booking_request_transitions (
    id TEXT PRIMARY KEY NOT NULL,
    booking_request_id TEXT NOT NULL,
    from_state TEXT,
    to_state TEXT NOT NULL,
    action TEXT NOT NULL,
    actor TEXT NOT NULL CHECK (actor IN ('customer', 'staff', 'payment_webhook', 'system')),
    note TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_booking_request_transitions_request_created ON booking_request_transitions (booking_request_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS booking_request_action_claims (
    booking_request_id TEXT NOT NULL,
    expected_version INTEGER NOT NULL CHECK (expected_version >= 0),
    action_key_hash TEXT NOT NULL CHECK (length(action_key_hash) = 64),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (booking_request_id, expected_version)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_action_claims_key ON booking_request_action_claims (action_key_hash)`,
  `CREATE TABLE IF NOT EXISTS admin_action_idempotency_keys (
    key_hash TEXT PRIMARY KEY NOT NULL CHECK (length(key_hash) = 64),
    request_hash TEXT NOT NULL CHECK (length(request_hash) = 64),
    booking_request_id TEXT NOT NULL,
    response_json TEXT NOT NULL CHECK (json_valid(response_json)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_admin_action_idempotency_request ON admin_action_idempotency_keys (booking_request_id)`,
  `CREATE TABLE IF NOT EXISTS booking_request_checkouts (
    id TEXT PRIMARY KEY NOT NULL,
    booking_request_id TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'provider_pending' CHECK (state IN ('provider_pending', 'awaiting_payment', 'processing', 'cancellation_pending', 'paid', 'expired', 'cancelled')),
    deposit_amount_cents INTEGER NOT NULL CHECK (deposit_amount_cents IN (10000, 30000)),
    currency TEXT NOT NULL DEFAULT 'AUD' CHECK (currency = 'AUD'),
    payment_provider TEXT,
    provider_checkout_id TEXT,
    provider_checkout_url TEXT CHECK (provider_checkout_url IS NULL OR provider_checkout_url LIKE 'https://%'),
    calendar_id_snapshot TEXT,
    expires_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE INDEX IF NOT EXISTS idx_booking_request_checkouts_request_id ON booking_request_checkouts (booking_request_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_checkouts_provider_checkout ON booking_request_checkouts (payment_provider, provider_checkout_id)`,
  `CREATE TABLE IF NOT EXISTS booking_request_payments (
    id TEXT PRIMARY KEY NOT NULL,
    booking_request_id TEXT NOT NULL,
    checkout_id TEXT NOT NULL,
    provider TEXT NOT NULL,
    provider_payment_id TEXT NOT NULL,
    amount_cents INTEGER NOT NULL CHECK (amount_cents IN (10000, 30000)),
    currency TEXT NOT NULL DEFAULT 'AUD' CHECK (currency = 'AUD'),
    status TEXT NOT NULL DEFAULT 'verified' CHECK (status = 'verified'),
    provider_receipt_url TEXT,
    verified_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_payments_request_id ON booking_request_payments (booking_request_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_payments_checkout_id ON booking_request_payments (checkout_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_payments_provider_payment ON booking_request_payments (provider, provider_payment_id)`,
  `CREATE TABLE IF NOT EXISTS booking_request_calendar_events (
    id TEXT PRIMARY KEY NOT NULL,
    booking_request_id TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'queued' CHECK (state IN ('queued', 'created', 'cancelled', 'failed')),
    calendar_id TEXT NOT NULL,
    provider_event_id TEXT,
    last_error_code TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_calendar_request_id ON booking_request_calendar_events (booking_request_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_booking_request_calendar_provider_event ON booking_request_calendar_events (calendar_id, provider_event_id)`,
  `CREATE TABLE IF NOT EXISTS appointment_reminder_jobs (
    id TEXT PRIMARY KEY NOT NULL,
    booking_request_id TEXT NOT NULL,
    reminder_kind TEXT NOT NULL CHECK (reminder_kind IN ('seven_days', 'twenty_four_hours')),
    due_at TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'scheduled' CHECK (state IN ('scheduled', 'processing', 'sent', 'cancelled', 'failed')),
    schedule_version INTEGER NOT NULL DEFAULT 1 CHECK (schedule_version >= 1),
    dispatched_at TEXT,
    cancelled_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_appointment_reminders_request_kind_version ON appointment_reminder_jobs (booking_request_id, reminder_kind, schedule_version)`,
  `CREATE INDEX IF NOT EXISTS idx_appointment_reminders_state_due ON appointment_reminder_jobs (state, due_at)`,
  `CREATE TABLE IF NOT EXISTS service_reminder_jobs (
    id TEXT PRIMARY KEY NOT NULL,
    booking_request_id TEXT NOT NULL,
    customer_profile_id TEXT,
    interval_months INTEGER NOT NULL CHECK (interval_months IN (6, 12)),
    due_at TEXT NOT NULL,
    state TEXT NOT NULL DEFAULT 'scheduled' CHECK (state IN ('scheduled', 'processing', 'sent', 'cancelled', 'unsubscribed', 'failed')),
    unsubscribe_token_hash TEXT NOT NULL CHECK (length(unsubscribe_token_hash) = 64),
    recipient_email_hash TEXT NOT NULL CHECK (length(recipient_email_hash) = 64),
    dispatched_at TEXT,
    unsubscribed_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_service_reminder_jobs_request_interval ON service_reminder_jobs (booking_request_id, interval_months)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS idx_service_reminder_jobs_unsubscribe_hash ON service_reminder_jobs (unsubscribe_token_hash)`,
  `CREATE INDEX IF NOT EXISTS idx_service_reminder_jobs_state_due ON service_reminder_jobs (state, due_at)`,
  `CREATE INDEX IF NOT EXISTS idx_service_reminder_jobs_customer_state ON service_reminder_jobs (customer_profile_id, state)`,
  `CREATE TABLE IF NOT EXISTS service_reminder_suppressions (
    recipient_email_hash TEXT PRIMARY KEY NOT NULL CHECK (length(recipient_email_hash) = 64),
    reason TEXT NOT NULL DEFAULT 'customer_unsubscribe' CHECK (reason IN ('customer_unsubscribe', 'staff_suppression')),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
  )`,
] as const;
